### ISSUE TITLE
PrimaryText not showing up when bubble list is in right/left display mode

### ISSUE THREAD

**Issue by allxie** [smollweide/react-speed-dial#12]
Hey,
Really enjoying this package and its documentation.
I'd been bashing my head against the wall trying to figure out why my primaryText elements weren't getting rendered, and found in your code that they don't get rendered if the list display direction is horizontal (left/right). It would be super-awesome-rad if...
a.) This could be in the documentation for primaryText
b.) The labels rendered anyway, but above/below
c.) They rendered anyway, but oriented diagonally/vertically above/below

Thanks!

**Comment by allxie** [comment]
I'm working on a pull request for the rendering anyway options.

**Comment by smollweide** [comment]
Hi @allxie,
you are right the text wasn't rendered if the alignment was "up" or "down".
I fixed that, but it's still not visible because that is wanted.
You can override the inline styles [example code](https://github.com/smollweide/react-speed-dial/blob/master/src/examples/example-bug11/example-bug11.js#L88).
`npm install react-speed-dial@latest --save` or `yarn add react-speed-dial@0.4.4 --save`

Thank you for your patience.
