### ISSUE TITLE
Add support for Material-UI v1.x

### ISSUE THREAD

**Issue by tkirda** [smollweide/react-speed-dial#23]
Any plans to support Material-UI v1?

**Comment by smollweide** [comment]
Hi @tkirda,
yes, but not before material-ui v1 is released.

**Comment by jarrodcolburn** [comment]
Hello. I'm really excited to use the Speed Dial. It looks awesome! But I am using Material-UI v1 also. I totally get where you're coming from on wanting to wait for final release.  But could you please help me know how to run both of them together? I keep getting clashing dependency error. saying "no such file ${ProjectRoot}/node_modules/material-ui/FloatingActionButton/index.js' because it doesn't exist in v1.  Is there any way to have the two packages co-exist with multiple versions of the Material-UI dependency? thanks.

**Comment by smollweide** [comment]
Hello,
Material UI in Version 1 use jss and 0.x.x use inline styles. That‘s why it‘s not a good idea to support both at the same time or better within one version. I‘m currently working on the new version.

**Comment by gknapp** [comment]
Currently on 0.x of Material UI for a production app. I'm waiting on a few components, including react-speed-dial, before upgrading. Subscribed to this issue.

**Comment by Sewdn** [comment]
@smollweide Any update on the progress for v1.x?
Thanks!

**Comment by smollweide** [comment]
Hello,
I pushed the current implementation here:
https://github.com/smollweide/material-ui-speed-dial

This is an example of how to use it:
https://github.com/smollweide/material-ui-speed-dial/blob/master/src/gh-pages/PageExampleBasic/PageExampleBasic.js
I'm using render-props for more flexibility but The downside is a lot of code.
To make this better I'm thinking about providing presets for the most common usages.
Please feel free to tell me your thoughts about it.

And the [demo](https://smollweide.github.io/material-ui-speed-dial/#/example-basic)

I renamed it to `material-ui-speed-dial` because the project is more related to material-ui than react.
Someone published `material-ui-speeddial` and this is too similar for npm. That's why I had to publish it with `@smollweide/material-ui-speed-dial`.

Thanks

**Comment by smollweide** [comment]
Hello, [material-ui-speed-dial](https://github.com/smollweide/material-ui-speed-dial) is ready for use.
